const supabaseUrl = 'https://cxekmhqrtebmzkelxjui.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4ZWttaHFydGVibXprZWx4anVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0MDU0NjAsImV4cCI6MjA1MTk4MTQ2MH0.eOuU6U31a5xLpZmn_llacEncJ7_Ho7SRPZjzH8iRZA4'
const supabaseClient = supabase.createClient(supabaseUrl, supabaseKey)
console.log(supabaseClient);

export default supabaseClient;